#!/bin/bash

# Usar sed "s/$FIND/$REPLACE/g" quando possível para maior legitividade
# Em hipótese alguma, o script deve falhar dentro do framework (comando 2>/dev/null || echo erro)
# Incluir versão aqui também Ex:(0.1.5)
# Usar cores (Função message)

#######################################################################
#                                                                     #
#                               CGIWork                               #
#                                                                     #
#  Description: Replace shell variables into an output file, keeping  #
#               your output files and shell scripts separated.        #
#                                                                     #
#  Usage: cgiwork output_file                                         #
#  Example: cgiwork templates/example.html                            #
#                                                                     #
#  Author: LBezerril                                                  #
#  To see the documentation, visit: github.com/LBezerril/CGIWork      #
#                                                                     #
#                                                                     #
#######################################################################

KEY_VALUE_ARRAY=( "$@" ); # ( "$1" )
OUTPUT_FILE="$2";
MESSAGE_ERROR="CGIWork Error:";

function replace_variables() {
	for key_value in "${KEY_VALUE_ARRAY[@]}"; do
		local key="";
		local key_expression="\${$key}";
		local value="$(echo "${value}" | sed 's/\\/\\\\/g;s/\//\\\//g;s/&/\\&/g')";
		local sedexpression+="s/${key_expression}/${value}/g;";
	done;
	cat "$OUTPUT_FILE" | sed "$sedexpression";
}

# $# -lt 1
if [[ "$#" -ne 1 ]]; then
	echo "$MESSAGE_ERROR Output file unspecified!";
	exit 1;
else
	if [[ ! -f "$OUTPUT_FILE" ]]; then
		echo "$MESSAGE_ERROR Output file does not exist!";
		exit 1;
	else
		if [[ ! -r "$OUTPUT_FILE" ]]; then
			echo "$MESSAGE_ERROR Output file is not readable!";
			exit 1;
		fi;
	fi;
fi;

replace_variables;
