#!/bin/bash

#######################################################################
#                                                                     #
#                               CGIWork                               #
#                                                                     #
#  Description: Replace shell variables into an output file, keeping  #
#               your output files and shell scripts separated.        #
#                                                                     #
#  Usage: cgiwork "${ARRAY[@]}"                                       #
#                                                                     #
#  Important: The output file must be the first element of the array  #
#  Example of array: ARRAY=("templates/example.html");                #
#                    ARRAY+=("variable1=value1");                     #
#                    ARRAY+=("variable2=value2");                     #
#                                                                     #
#  Author: LBezerril                                                  #
#  To see the documentation, visit: github.com/LBezerril/CGIWork      #
#                                                                     #
#                                                                     #
#######################################################################

ARRAY=( "$@" );
PROPERTIES="${ARRAY[0]}" && unset ARRAY[0];
EXPECTED_VALUES="plain|json|xml";
PATH=$PATH:/opt/cgiwork/scripts
MESSAGE_ERROR="CGIWork Error:";

function get_property() {
	# $1: property name
	echo "$PROPERTIES" | grep -Eo "$1=(.*);" | sed "s/$1=//g;s/;.*//g";
}

function is_expected_value() {
	# $1: value
	# $2: expected values separated by "|"
	echo "$1" | grep -Eq "^($2)$";
}

function var_is_null() {
	# $1: variable;
	if [[ "$1" != "" ]]; then	return 1; fi;
}

TYPE="$(get_property type)";

if ! $(is_expected_value $TYPE $EXPECTED_VALUES); then
	echo "$MESSAGE_ERROR Invalid type!";
	exit 1;
fi;

. cgiwork_$TYPE;
