#!/bin/sh

# Lista de módulos suportados. O nome do módulo corresponse ao sufixo do nome
# do script a ser carregado.
__MODULES="checking request response body"

# Verifica se o módulo deverá ser carregado.
__load_module() {
  # $1: Módulo a ser validado.
  # $@: Lista de módulos passados para o framework.

  # Se nenhum módulo for passado na inicialização do framework, carrega todos.
  [ -z $2 ] && return 0

  local module=$1
  shift

  local i
  for i in $@; do
    [ $module = $i ] && return 0
  done

  return 1
}

# Primeiro método do framework a ser chamado. Gerencia quais módulos irão ser
# carregados.
__start() {
  # stdin: Lista de módulos passados para o framework.

  local modules
  [ -t 0 ] || read modules

  local i
  for i in $__MODULES; do
    # Caso __load_module retorne 0, carrega o respectivo módulo.
    __load_module $i $modules && . cgiwork_$i
  done
}

__start

# Remove constante e funções que não serão mais usadas.
unset -v __MODULES
unset -f __load_module __start
