#!/bin/sh

# variaveis globais (?)

echo "cgiwork_response"


# _set sem argumento
#_set_protocol "HTT/1.1"
#_set_status 200
#_set_status 200 "OK"
#_set_header "Content-type" "text/html"
#_set_headers $ARRAY # Será necessário ?
# Commita headers (echo "\n") - Define headers default
#_flush_buffer
