#!/bin/sh

echo "cgiwork_body"





# TODO: Definir nome desta função
#ARRAY+=("visitor_number=$RANDOM");
#_tag_page "template.html" $ARRAY
#cat template.html | _tag_page $ARRAY


# Json e XML
#_marshal_json $ARRAY # Retorna formato json
#cat template.json | _unmarshal_json # Retorna objeto array



# TODO: echos não serão echoados até chamar esta função, permitindo assim setar
# o status code depois de montar o body (REST)
#_flush_body
