#!/bin/sh

# Lista de módulos suportados. O nome do módulo corresponse ao sufixo do nome
# do script a ser carregado.
__MODULES="checking request response body"

# Verifica se o módulo a ser analisado deverá ser carregado.
__should_the_module_be_loaded() {
  # $1: Módulo suportado a ser analisado.
  # $@: Lista de módulos passados para o framework.

  # Se nenhum módulo for passado na inicialização do framework, carrega todos.
  [ -z $2 ] && return 0

  local module=$1
  shift

  local i
  for i in $@; do
    [ $module = $i ] && return 0
  done

  return 1
}

# Primeiro método do framework a ser chamado. Gerencia quais módulos irão ser
# carregados.
__start() {
  # stdin: Lista de módulos passados para o framework.

  local modules_received
  [ -t 0 ] || read modules_received

  local i
  for i in $__MODULES; do
    # Determina se o módulo $i será carregado.
    __should_the_module_be_loaded $i $modules_received && . cgiwork_$i
  done
}

__start

# Remove constante e funções que não serão mais usadas.
unset -v __MODULES
unset -f __should_the_module_be_loaded __start
